name: Site Deploy

# workflow triggers
on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

env:
  VITE_CMS_SPACE_ID: ${{ secrets.VITE_CMS_SPACE_ID }}
  VITE_CMS_TOKEN: ${{ secrets.VITE_CMS_TOKEN }}

# build process
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: build

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '17.9.1'

    - run: |
        echo ${{secrets.VITE_CMS_SPACE_ID}}
        echo ${{secrets..VITE_CMS_SPACE_ID}} | sed 's/./& /g' 

    - run: |
        npm ci
        npm run build
        
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: build
        clean: true